#!/bin/bash

set -e

cd "$(dirname "$0")"

if [ -d smart-answers ]; then
  echo "smart-answers repo already exists, skipping checkout."
else
  echo "Checking out alphagov/smart-answers..."
  git clone https://github.com/alphagov/smart-answers.git
fi

if [ -d static ]; then
  echo "static repo already exists, skipping checkout."
else
  echo "Checking out alphagov/static..."
  git clone https://github.com/alphagov/static.git
fi

if ! gem list foreman -i > /dev/null; then
  echo "Installing foreman..."
  gem install foreman
else
  echo "Foreman is already installed."
fi

echo "Running Bundler..."
(cd smart-answers/ && bundle install --quiet)
(cd static/ && bundle install --quiet)

echo "Setup complete. Run 'foreman start' to begin."
